### ISSUE TITLE
offline support

### ISSUE THREAD

**Issue by hworld** [gamejolt/gamejolt#116]

**Comment by YLivay** [comment]
not simple at all, more to it than initially thought haha.
client library vuex needs to be bootstrapped regardless of user context,
need to figure out if it ever needs clearing.
thumbnails need to be cached at multiple sizes for installed/followed games so that the offline pages displaying them would load properly, need to be able to gracefully handle the request in game overview for package info to load it from indexeddb (there may be an issue with some fields not being available like _build because it doesn't get reconstructed by dexie the way it usually does) and more.

**Comment by hworld** [comment]
Not caching multiple thumbnails yet since old client doesn't either.
Also game pages never worked offline. Only the installed games page.

**Comment by hworld** [comment]
yeah, did this somehow
