### ISSUE TITLE
How to do broadcasts for client?

### ISSUE THREAD

**Issue by hworld** [gamejolt/gamejolt#165]

**Comment by YLivay** [comment]
we need to skip the broadcast check for now. The issue is that the client doesn't know which of the posts are actually relevant to it. e.g. right after pushing a feature it wont be available in the client right away,  and  when updating from  older versions of the client we dont know which broadcasts in the middle we added  support for.

We'll  figure out a solution , but for now  we're not holding back client release for this because this isn't a regression.
