### ISSUE TITLE
Gamejolt client windows: nw-gyp compile error.

### ISSUE THREAD

**Issue by luckcolors** [gamejolt/gamejolt#18]
Hello again.
This time i'm tring to build the desktop app but of course it throws an error.
Here's the console ouput (apparently there isn't a way to make gulp more verbose so i'm sorry if there's some lack of info):
Command(all dependencies where installed): gulp --production --client --arch=32
[error.log.zip](https://github.com/gamejolt/gamejolt/files/99852/error.log.zip)
Note: Mine is a clean windows install. 
Also i have set the variable for gyp compiler as follows: GYP_MSVS_VERSION=2015

**Comment by addaleax** [comment]
@luckcolors This is essentially nwjs/nw.js#4033, with a PR available bug not merged at nwjs/nw-gyp#81.

For the project maintainers: I just saw that you inserted some gulp task for re-compiling lzma-native for nw.js. Since v1.0.0, I use node-pre-gyp to provide pre-compiled binaries; I think I can look into supporting nw.js for that (so you don’t need to re-compile anything in most cases). Would you be interested?

**Comment by hworld** [comment]
We could do that @addaleax, but I wouldn't want to give your more work than you'd need. nwjs is kind of a nightmare with compiled libs. I think it needs to be done per nwjs version, so it's probably not worth it to push precompiled. We do the compilation during the build here: https://github.com/gamejolt/gamejolt/blob/b38405c5ad672444c7d78f69ac50b1b71840237c/tasks/client.js#L181

It gets even crazier on Windows because you have to patch the compiled lib if you want to have an executable name for your application other than nw.exe. I guess they're fixing this on the new version that's in beta. We do that here in our build process: https://github.com/gamejolt/gamejolt/blob/b38405c5ad672444c7d78f69ac50b1b71840237c/tasks/client.js#L185

@luckcolors You can do a build using the command: `npm run client-build-win`. This calls the gulp build with all the correct options. However, currently it's exactly what you're calling, anyway. But in the future it'll make sure that you're in sync with what I run myself.

 Either way, I think I know what's happening. In your logs I see this:

```
gyp ERR! command "D:\\DevTools\\nodejs\\node.exe" "D:\\DevTools\\nodejs\\node_modules\\nw-gyp\\bin\\nw-gyp.js" "clean" "configure" "build" "--target=0.12.3" "--arch=ia32"
gyp ERR! cwd C:\Users\luckcolors\Desktop\gamejolt\build\client\prod\source\node_modules\lzma-native
gyp ERR! node -v v5.4.1
gyp ERR! nw-gyp -v v0.13.0
```

I'm mainly looking at `gyp ERR! nw-gyp -v v0.13.0` I think you installed latest nw-gyp, which is actually the one that works with the latest nwjs beta that isn't stable yet. They changed the API completely and it's not backwards compatible.

Would you be able to do `npm i -g nw-gyp@0.12.3` instead? We may have to start including nw-gyp at the correct version in the package.json so we can call it within the project and ensure correct version. I haven't done that yet because I was trying to reduce the amount of packages needed to download to get up and running with a build of the site. Might be the better thing to do, though...

Let me know if that works for you.

**Comment by addaleax** [comment]
@hworld Well, I don’t have to do it manually, I let Travis CI & co run the builds for me, but yeah, it needs to be done for each relevant nw.js version & architecture. Still, if it helps with build problems like this, it might be worth it… I’ll be looking into it, if you don’t mind. Whether you’ll use it or not is up to you, anyway. :)

And for the build problem above, I’m pretty sure the relevant lines are
```
…
  File "D:\DevTools\nvm\v5.4.1\node_modules\nw-gyp\gyp\pylib\gyp\generator\msvs.py", line 1798, in CalculateVariables
    generator_flags.get('msvs_version', 'auto'))
  File "D:\DevTools\nvm\v5.4.1\node_modules\nw-gyp\gyp\pylib\gyp\MSVSVersion.py", line 400, in SelectVisualStudioVersion
    versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)
KeyError: '2015'
gyp ERR! configure error
```
i.e. it really is the current lack of support for MSVS 2015 in nw-gyp.

**Comment by luckcolors** [comment]
Ok so i tried again and i chaged the nw-gyp version as you suggested to  v0.12.3.
I also patched the MSVSversion.py as said here nwjs/nw.js#4033. (i also deleted the .pyc)
And this is the new build log:
[error2.zip](https://github.com/gamejolt/gamejolt/files/100991/error2.zip)

**Comment by addaleax** [comment]
@luckcolors Ah, sorry, this one is somewhat my fault that I didn’t see the re-compilation script mentioned by @hworld earlier – see https://github.com/nwjs/nw.js/wiki/Build-native-modules-with-nw-gyp for a bit of an explanation (i.e. the switch to node-pre-gyp required changes to the build system here).

@hworld I’ll make PRs here and at gamejolt/client-voodoo and include a newer version of my library, since providing pre-built binaries for nw.js actually seems to be quite feasible. You can, of course, stick to compiling the library each time someone runs the build tasks, but I think this will make things easier for everyone involved. :)
